### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by BrekiTomasson** [bulldog98/soulcapture#5]
Will there be a new version of this coming soon? The one on CurseForge does not have your updated language file implemented, and there doesn't seem to be any way of getting the enchantment in-game - or have I just managed to miss it?

**Comment by bulldog98** [comment]
I'll look into releasing a new version, at least with the language file fixes. I'll look more into the enchanting in-game.

**Comment by bulldog98** [comment]
The new version is out at curseforge.
